# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9907da9db29df5f46a08ed56dac8f8db94d5dd36f953db4430c18c29a3b1b8c266ce8dcdb31723c52855a925136aaf41d115dce79c46f1f9eb703dca4e6b0fee
  json_web_token_secret: cabfa4559f1d674ee86e423a4a849f450393630dfc2c48b2a949efb8df510357f602b5cab6584668452d7e0eba961d5c88be6194d978eb1d7d5d55ce5ecbc204

test:
  secret_key_base: d08d850b99f6bdd802c0168070e78585ab84647205c643c905b31f05b2fc9f37261a8b820d306cfffc7806adbbec80abd1b56778db75ad1b038dee949cbf3b3a
  json_web_token_secret: 3f75df1558de8e0f3cc2468df2742026c88ed78df7cb1d5e957982c2c69687a38676c7f44b8caba78b7ee75acb3e401f277b242c12a9756d62a04a91186d59b4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV.fetch("SECRET_KEY_BASE") if Rails.env.production? %>
  json_web_token_secret: <%= ENV.fetch('JSON_WEB_TOKEN_SECRET') if Rails.env.production? %>
